version: '3.8'

networks:
  sep4-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  tcp-listener:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final-tcp
      args:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        SERVER_ADDRESS: 172.28.0.2
    ports:
      - "6868:6868"
    networks:
      sep4-network:
        ipv4_address: 172.28.0.2

  web-api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final-web
      args:
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        SERVER_ADDRESS: 172.28.0.2
    ports:
      - "80:80"
    networks:
      sep4-network:
        ipv4_address: 172.28.0.3