networks:
  sep4-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:

  website:
    image: oliwierwijas/smart-home-frontend:latest
    ports:
      - "80:80"
    networks:
      sep4-network:
        ipv4_address: 172.28.0.4

  tcp-listener:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final-tcp
      args:
        DATABASE_HOST: smart-homel.postgres.database.azure.com
        DATABASE_NAME: smart_home
        DATABASE_USER: sep_user
        DATABASE_PASSWORD: Semester4Password
        SERVER_ADDRESS: 172.28.0.2
    ports:
      - "6868:6868"
    networks:
      sep4-network:
        ipv4_address: 172.28.0.2

  web-api:
    build: 
      context: .
      dockerfile: Dockerfile
      target: final-web
      args:
        DATABASE_HOST: smart-homel.postgres.database.azure.com
        DATABASE_NAME: smart_home
        DATABASE_USER: sep_user
        DATABASE_PASSWORD: Semester4Password
        SERVER_ADDRESS: 172.28.0.2
    ports:
      - "80:80"
    networks:
      sep4-network:
        ipv4_address: 172.28.0.3