apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: sep4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: oliwierwijas/smart-home-frontend:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 3000