apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-listener
  template:
    metadata:
      labels:
        app: tcp-listener
    spec:
      containers:
      - name: tcp-listener
        image: tcp-listener:latest
        ports:
        - containerPort: 6868