apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-listener
  namespace: sep4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-listener
  template:
    metadata:
      labels:
        app: tcp-listener
    spec:
      containers:
      - name: tcp-listener
        image: vlaad08/smart-home-server:latest
        ports:
        - containerPort: 6868