apiVersion: v1
kind: Service
metadata:
  name: tcp-listener
  namespace: sep4
spec:
  type: LoadBalancer
  selector:
    app: tcp-listener
  ports:
    - protocol: TCP
      port: 6868
      targetPort: 6868