apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  namespace: sep4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: vlaad08/smart-home:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_HOST
          value: "smart-homel.postgres.database.azure.com"
        - name: DATABASE_NAME
          value: "smart_home"
        - name: DATABASE_USER
          value: "sep_user"
        - name: DATABASE_PASSWORD
          value: "Semester4Password"
        - name: SERVER_ADDRESS
          value: "127.0.0.1"