apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  namespace: sep4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: vlaad08/smart-home:latest
        ports:
        - containerPort: 80
        args:
        - "--DATABASE_HOST=  ${{ secrets.DATABASE_HOST }}"
        - "--DATABASE_NAME= ${{ secrets.DATABASE_NAME }}"
        - "--DATABASE_USER= ${{ secrets.DATABASE_USER }}"
        - "--DATABASE_PASSWORD= ${{ secrets.DATABASE_PASSWORD }}"
        - "--SERVER_ADDRESS=tcp-listener.sep4.svc.cluster.local"