apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: sep4
spec:
  type: LoadBalancer
  selector:
    app: web-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000