name: Docker build and push

on:
  pull_request:
    branches: [ "BACKEND", "main" ]
  push:
    branches: [ "BACKEND", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push TCPListener
        uses: docker/build-push-action@v5
        with:
          context: ./Backend-SEP4
          file: ./Backend-SEP4/Dockerfile
          target: final-tcp
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-home-server:latest
          build-args: |
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
      -
        name: Build and push WebAPI
        uses: docker/build-push-action@v5
        with:
          context: ./Backend-SEP4
          file: ./Backend-SEP4/Dockerfile
          target: final-web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-home:latest
          build-args: |
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
