name: Docker build and push

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push TCPListener
        uses: docker/build-push-action@v5
        with:
          context: ./Backend-SEP4
          file: ./Backend-SEP4/Dockerfile
          target: final-tcp
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-home-server:v1
          build-args: |
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            SERVER_ADDRESS=127.0.0.1
            WEB_API_ADDRESS=${{ secrets.WEB_API_ADDRESS }}
      -
        name: Build and push WebAPI
        uses: docker/build-push-action@v5
        with:
          context: ./Backend-SEP4
          file: ./Backend-SEP4/Dockerfile
          target: final-web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smart-home:v1
          build-args: |
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USER=${{ secrets.DATABASE_USER }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}
