name: PlatformIO Build

on:
  push: 
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio

    - name: Change to IoT project directory
      run: cd sep4-IoT
    
    - name: Run PlatformIO Build
      run: |
        pio run

    - name: Upload PlatformIO Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: .pio/build/uno/firmware.hex

