name: PlatformIO Build

on:
  push: 
    branches: ['IoT-TestAlarm']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Run PlatformIO Build
      run: |
        cd sep4-IoT
        pio run -e target_run

    - name: Run PlatformIO Tests
      run: |
        cd sep4-IoT
        platformio test --environment target_native

    - name: Upload PlatformIO Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: sep4-IoT/.pio/build

